basePath: /
definitions:
  controller.AuthSigninReq:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  controller.CommentNewReq:
    properties:
      body:
        type: string
      postId:
        type: integer
    required:
    - body
    - postId
    type: object
  controller.CommentUpdateReq:
    properties:
      body:
        type: string
    required:
    - body
    type: object
  controller.ErrorResponse:
    properties:
      message:
        type: string
    required:
    - message
    type: object
  controller.PostUpdateRequest:
    properties:
      body:
        type: string
      title:
        maxLength: 100
        type: string
    required:
    - body
    - title
    type: object
  controller.UserCreateReq:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  entity.Comment:
    properties:
      body:
        type: string
      created_at:
        format: date-time
        type: string
      id:
        type: integer
      post_id:
        type: integer
      updated_at:
        format: date-time
        type: string
      user_id:
        type: integer
    required:
    - body
    - created_at
    - id
    - post_id
    - updated_at
    - user_id
    type: object
  entity.Post:
    properties:
      body:
        type: string
      comments:
        items:
          $ref: '#/definitions/entity.Comment'
        type: array
      created_at:
        format: date-time
        type: string
      id:
        type: integer
      image_url:
        type: string
      like_count:
        type: integer
      title:
        type: string
      updated_at:
        format: date-time
        type: string
      user_id:
        type: integer
      username:
        type: string
    required:
    - body
    - comments
    - created_at
    - id
    - image_url
    - like_count
    - title
    - updated_at
    - user_id
    - username
    type: object
  entity.User:
    properties:
      id:
        type: integer
      username:
        type: string
    required:
    - id
    - username
    type: object
info:
  contact: {}
  description: このswaggerはweb application演習5班のAPI仕様書です。
  title: web-application team 5 API
  version: "1.0"
paths:
  /comments:
    post:
      consumes:
      - application/json
      description: サインインしているユーザーで、指定された投稿に、本文のコメントを作成する
      parameters:
      - description: リクエストパラメータ
        in: body
        name: commentNew
        required: true
        schema:
          $ref: '#/definitions/controller.CommentNewReq'
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: new comment API
      tags:
      - comments
  /comments/{commentID}:
    delete:
      consumes:
      - application/json
      description: サインインしているユーザーで、指定されたコメントを削除する
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: delete comment API
      tags:
      - comments
    put:
      consumes:
      - application/json
      description: サインインしているユーザーで、指定されたコメントを更新する
      parameters:
      - description: リクエストパラメータ
        in: body
        name: commentUpdate
        required: true
        schema:
          $ref: '#/definitions/controller.CommentUpdateReq'
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: update comment API
      tags:
      - comments
  /posts:
    get:
      consumes:
      - application/json
      description: 投稿一覧を取得します
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Post'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: get list posts
      tags:
      - posts
    post:
      consumes:
      - application/json
      description: サインインしているユーザーで、指定されたタイトル、本文の投稿を作成する
      parameters:
      - in: formData
        name: body
        required: true
        type: string
      - in: formData
        maxLength: 100
        name: title
        required: true
        type: string
      - description: 画像ファイル
        in: formData
        name: image
        type: file
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: new post API
      tags:
      - posts
  /posts/{postID}:
    delete:
      description: 投稿を削除する
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: delete post API
      tags:
      - posts
    get:
      consumes:
      - application/json
      description: 投稿の詳細を取得します
      parameters:
      - description: Post ID
        in: path
        name: postID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Post'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: get post detail
      tags:
      - posts
    put:
      consumes:
      - application/json
      description: 投稿を更新します。
      parameters:
      - description: リクエストパラメータ
        in: body
        name: postUpdate
        required: true
        schema:
          $ref: '#/definitions/controller.PostUpdateRequest'
      - description: Post ID
        in: path
        name: postID
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: update post
      tags:
      - posts
  /posts/{postID}/like:
    post:
      description: 投稿に対して、いいねを付与します。
      parameters:
      - description: Post ID
        in: path
        name: postID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: get list posts
      tags:
      - posts
  /signin:
    post:
      consumes:
      - application/json
      description: usernameとpasswordでsigninします。
      parameters:
      - description: リクエストパラメータ
        in: body
        name: signinPost
        required: true
        schema:
          $ref: '#/definitions/controller.AuthSigninReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: singin API
      tags:
      - auth
  /users:
    post:
      consumes:
      - application/json
      description: usernameとpasswordでuserを作成します。
      parameters:
      - description: リクエストパラメータ
        in: body
        name: userCreate
        required: true
        schema:
          $ref: '#/definitions/controller.UserCreateReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Create User API
      tags:
      - users
  /users/me:
    get:
      description: ログインしているユーザーの情報を取得します
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.User'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: get user me
      tags:
      - users
swagger: "2.0"
