name: Frontend CI with Biome

on:
  pull_request:
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
          working-dir: "./frontend/"
      - name: Run Biome
        run: biome ci ./src/ --config-path=./biome.json